// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfbdexwxeidpwpyerjoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYmRleHd4ZWlkcHdweWVyam9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjA2MTAsImV4cCI6MjA3MzQ5NjYxMH0.drXLA8yFK_fDMrcMST1z-JyOilpmA9wNH24r4L4Rrws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});